server:
  port: 8001
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml4
#  type-aliases-package: com.scu.springcloud.pojo
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka